#MSTAR TOUCHSCREEN DRIVER

obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_hotknot.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_hotknot_queue.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_jni_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_mp_test.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_qcom.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR)		+= mstar_drv_utility_adaption.o
